export enum ErrorCode {
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_INACTIVE = 'AUTH_USER_INACTIVE',
  USER_HAS_NO_ROLE_OR_PERMISSIONS = 'USER_HAS_NO_ROLE_OR_PERMISSIONS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_INVALID_EMAIL_OR_ALREADY_EXISTS = 'USER_INVALID_EMAIL_OR_ALREADY_EXISTS',
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
