services:
  database:
    image: bitnami/postgresql:latest
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRESQL_DATABASE: ${PG_NAME}
      POSTGRESQL_USERNAME: ${PG_USER}
      POSTGRESQL_PASSWORD: ${PG_PASSWORD}
      POSTGRESQL_POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRESQL_TIMEZONE: ${TZ}
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
